### ISSUE TITLE
Allods server 4.0

### ISSUE THREAD

**Issue by sosigesss** [Sorok-Dva/AllodsNovaServer#2]
Salut. Je m'appelle Egor, je viens de Russie. Je joue à Allods depuis la version 3.0 et j'essaye récemment d'exécuter un serveur local sur la version 4.0.02 pour récupérer du temps avec des amis. Mais les fichiers du serveur ne sont pas accessibles au public. Mais je suis tombé sur votre message: https://community.allods-developers.eu/threads/4-0-02-42-allods-online-server-usgala.452/. Si je comprends bien, c'est exactement ce dont j'ai besoin. Voulez-vous m'aider à m'aider?
postscript désolé pour mon français (google translate)

**Comment by sosigesss** [comment]
Je me suis inscrit sur votre site (login: sosigesss) et j'ai des fichiers allods 4.0.02 allodspotatos, je peux les télécharger sur votre site et peut-être que cela aidera quelqu'un (je n'ai pas encore pu lancer)

**Comment by sosigesss** [comment]
Merci!

**Comment by Sorok-Dva** [comment]
Oh sorry I didn't see you issue notification (glad I'm more reactive on ADC board 😬)
I don't know if you have managed to share what you wanted but don't hesitate to reach me through discord if you need help (via ADC discord server)
